apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: voting-app
  labels:
    name: result-service
    app: demo-voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app
